version: '3'

services:
  web:
    build: 
      context: ./.docker
      dockerfile: web.docker
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      
  app:
    build: 
      context: ./.docker
      dockerfile: app.docker
    container_name: app
    volumes:
      - .:/var/www
    logging:
      options:
        max-size: "10m"
        max-file: "1"

  pgsql:
    build: 
      context: ./.docker
      dockerfile: database.docker
    container_name: pgsql
    hostname: pgsql
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    logging:
      options:
        max-size: "1m"
        max-file: "1"